package com.aiflow.enterprise.ai;

public enum AIRequestType {
    APPROVAL_RECOMMENDATION,
    REQUEST_SUMMARY,
    DECISION_EXPLANATION,
    OUTCOME_PREDICTION,
    APPROVER_RECOMMENDATION,
    WORKFLOW_OPTIMIZATION,
    BOTTLENECK_DETECTION,
    INSIGHT_GENERATION,
    CONVERSATIONAL_QUERY
}
