package com.aiflow.enterprise.enums;

public enum AuditActionType {

    // Authentication & Session
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    TOKEN_REFRESHED,
    SESSION_CREATED,
    SESSION_EXPIRED,
    SESSION_REVOKED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_VERIFIED,
    MFA_FAILED,

    // User Management
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_VERIFIED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    ROLE_CHANGED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,

    // Workflow
    WORKFLOW_CREATED,
    WORKFLOW_UPDATED,
    WORKFLOW_DELETED,
    WORKFLOW_PUBLISHED,
    WORKFLOW_ARCHIVED,
    WORKFLOW_CLONED,
    WORKFLOW_VALIDATED,
    WORKFLOW_STEP_ADDED,
    WORKFLOW_STEP_UPDATED,
    WORKFLOW_STEP_REMOVED,

    // Workflow Execution
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    EXECUTION_FAILED,
    EXECUTION_CANCELLED,
    EXECUTION_PAUSED,
    EXECUTION_RESUMED,
    EXECUTION_RETRIED,
    EXECUTION_SKIPPED,
    EXECUTION_TIMEOUT,

    // Approvals
    APPROVAL_SUBMITTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    APPROVAL_RETURNED,
    APPROVAL_DELEGATED,
    APPROVAL_ESCALATED,
    APPROVAL_SKIPPED,
    APPROVAL_WITHDRAWN,

    // Tasks
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_ASSIGNED,
    TASK_REASSIGNED,
    TASK_COMPLETED,
    TASK_PRIORITY_CHANGED,
    TASK_STATUS_CHANGED,
    TASK_COMMENT_ADDED,
    TASK_ATTACHMENT_ADDED,

    // Documents & Files
    DOCUMENT_UPLOADED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_DELETED,
    DOCUMENT_UPDATED,
    DOCUMENT_VIEWED,
    DOCUMENT_SHARED,
    DOCUMENT_EXTRACTED,
    DOCUMENT_ARCHIVED,
    DOCUMENT_RESTORED,
    FILE_UPLOADED,
    FILE_DELETED,

    // API Access
    API_ACCESSED,
    API_KEY_CREATED,
    API_KEY_REVOKED,
    API_KEY_EXPIRED,
    API_RATE_LIMIT_HIT,
    API_ENDPOINT_CALLED,

    // Configuration Changes
    CONFIG_CREATED,
    CONFIG_UPDATED,
    CONFIG_DELETED,
    ORGANIZATION_SETTINGS_CHANGED,
    SYSTEM_SETTINGS_CHANGED,
    INTEGRATION_CONFIGURED,
    INTEGRATION_DISABLED,
    FEATURE_FLAG_TOGGLED,

    // Webhook Execution
    WEBHOOK_CALLED,
    WEBHOOK_COMPLETED,
    WEBHOOK_FAILED,
    WEBHOOK_RETRIED,
    WEBHOOK_CIRCUIT_OPENED,
    WEBHOOK_CIRCUIT_HALF_OPENED,
    WEBHOOK_CIRCUIT_CLOSED,

    // AI & Recommendations
    AI_RECOMMENDATION_GENERATED,
    AI_RECOMMENDATION_ACCEPTED,
    AI_RECOMMENDATION_REJECTED,
    AI_RECOMMENDATION_OVERRIDDEN,
    AI_DECISION_MADE,
    AI_MODEL_CHANGED,
    AI_FEEDBACK_SUBMITTED,
    AI_INSIGHT_GENERATED,

    // Data Updates
    DATA_CREATED,
    DATA_UPDATED,
    DATA_DELETED,
    DATA_EXPORTED,
    DATA_IMPORTED,
    DATA_BACKUP,
    DATA_RESTORE,
    DATA_ARCHIVED,
    DATA_MERGED,
    DATA_VALIDATED,

    // Fraud Detection
    FRAUD_CHECK_TRIGGERED,
    FRAUD_ALERT_CREATED,
    FRAUD_ALERT_RESOLVED,
    FRAUD_ALERT_DISMISSED,
    FRAUD_RULE_CREATED,
    FRAUD_RULE_UPDATED,
    FRAUD_RULE_DELETED,
    FRAUD_RULE_ENABLED,
    FRAUD_RULE_DISABLED,
    FRAUD_REVIEW_COMPLETED,
    FRAUD_ML_PREDICTION,

    // Notifications
    NOTIFICATION_SENT,
    NOTIFICATION_READ,
    NOTIFICATION_DISMISSED,
    NOTIFICATION_PREFERENCE_CHANGED,
    NOTIFICATION_TEMPLATE_CREATED,
    NOTIFICATION_TEMPLATE_UPDATED,
    NOTIFICATION_SCHEDULED,
    NOTIFICATION_DELIVERED,
    NOTIFICATION_FAILED,
    NOTIFICATION_CHANNEL_CONFIGURED,

    // Organization Management
    ORGANIZATION_CREATED,
    ORGANIZATION_UPDATED,
    ORGANIZATION_DELETED,
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_DELETED,
    TEAM_CREATED,
    TEAM_UPDATED,
    TEAM_DELETED,
    BUSINESS_UNIT_CREATED,
    BUSINESS_UNIT_UPDATED,
    BUSINESS_UNIT_DELETED,
    EMPLOYEE_PROFILE_CREATED,
    EMPLOYEE_PROFILE_UPDATED,
    EMPLOYEE_PROFILE_DELETED,

    // Triggers
    TRIGGER_CREATED,
    TRIGGER_UPDATED,
    TRIGGER_DELETED,
    TRIGGER_ENABLED,
    TRIGGER_DISABLED,
    TRIGGER_EXECUTED,
    TRIGGER_FAILED,

    // Access Control
    ACCESS_GRANTED,
    ACCESS_DENIED,
    ACCESS_REVOKED,
    IP_WHITELISTED,
    IP_BLOCKED,
    RATE_LIMIT_EXCEEDED,
    SUSPICIOUS_ACTIVITY_DETECTED,

    // Import/Export
    EXPORT_INITIATED,
    EXPORT_COMPLETED,
    EXPORT_FAILED,
    IMPORT_INITIATED,
    IMPORT_COMPLETED,
    IMPORT_FAILED,
    REPORT_GENERATED,

    // System
    SYSTEM_STARTUP,
    SYSTEM_SHUTDOWN,
    SYSTEM_ERROR,
    SYSTEM_MAINTENANCE,
    SYSTEM_CONFIG_CHANGED,
    DATABASE_MIGRATION,
    CACHE_CLEARED,
    BACKUP_CREATED,
    BACKUP_RESTORED
}
