export enum UserRole {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  OPERATOR = "OPERATOR",
  FINANCE = "FINANCE",
  AUDITOR = "AUDITOR",
  VIEWER = "VIEWER",
  USER = "USER",
}

export enum WorkflowStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
  DELETED = "DELETED",
}

export enum ExecutionStatus {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
  SUSPENDED = "SUSPENDED",
  TIMED_OUT = "TIMED_OUT",
}

export enum RequestStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
  WITHDRAWN = "WITHDRAWN",
  IN_REVIEW = "IN_REVIEW",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  ESCALATED = "ESCALATED",
  ON_HOLD = "ON_HOLD",
  COMPLETED = "COMPLETED",
  CLOSED = "CLOSED",
}

export enum TaskStatus {
  PENDING = "PENDING",
  ASSIGNED = "ASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
  BLOCKED = "BLOCKED",
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum StepType {
  APPROVAL = "APPROVAL",
  NOTIFICATION = "NOTIFICATION",
  CONDITION = "CONDITION",
  DELAY = "DELAY",
  LOOP = "LOOP",
  WEBHOOK = "WEBHOOK",
  TASK = "TASK",
  EMAIL = "EMAIL",
  SMS = "SMS",
  FORM = "FORM",
  CALCULATION = "CALCULATION",
  TRANSFORMATION = "TRANSFORMATION",
  AI_DECISION = "AI_DECISION",
  DOCUMENT_PROCESSING = "DOCUMENT_PROCESSING",
  SUB_PROCESS = "SUB_PROCESS",
  TIMER = "TIMER",
  ESCALATION = "ESCALATION",
  TERMINATE = "TERMINATE",
  SCRIPT = "SCRIPT",
}

export enum TriggerType {
  SCHEDULED = "SCHEDULED",
  EVENT = "EVENT",
  WEBHOOK = "WEBHOOK",
  EMAIL = "EMAIL",
  MANUAL = "MANUAL",
}

export enum FraudRiskLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum FraudStatus {
  PENDING = "PENDING",
  REVIEWED = "REVIEWED",
  DISMISSED = "DISMISSED",
  CONFIRMED = "CONFIRMED",
}

export enum DocumentType {
  INVOICE = "INVOICE",
  RECEIPT = "RECEIPT",
  CONTRACT = "CONTRACT",
  REPORT = "REPORT",
  FORM = "FORM",
  LETTER = "LETTER",
  CERTIFICATE = "CERTIFICATE",
  ID_PROOF = "ID_PROOF",
  STATEMENT = "STATEMENT",
  OTHER = "OTHER",
}

export enum ProcessingStatus {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED",
}

export enum FieldType {
  TEXT = "TEXT",
  NUMBER = "NUMBER",
  DATE = "DATE",
  BOOLEAN = "BOOLEAN",
  SELECT = "SELECT",
  MULTI_SELECT = "MULTI_SELECT",
  FILE = "FILE",
  USER = "USER",
  DEPARTMENT = "DEPARTMENT",
  EMAIL = "EMAIL",
  PHONE = "PHONE",
  CURRENCY = "CURRENCY",
}

export enum AIRequestType {
  APPROVAL_RECOMMENDATION = "APPROVAL_RECOMMENDATION",
  SUMMARIZATION = "SUMMARIZATION",
  DECISION_EXPLANATION = "DECISION_EXPLANATION",
  OUTCOME_PREDICTION = "OUTCOME_PREDICTION",
  APPROVER_RECOMMENDATION = "APPROVER_RECOMMENDATION",
  WORKFLOW_OPTIMIZATION = "WORKFLOW_OPTIMIZATION",
  BOTTLENECK_DETECTION = "BOTTLENECK_DETECTION",
  INSIGHT_GENERATION = "INSIGHT_GENERATION",
  TREND_ANALYSIS = "TREND_ANALYSIS",
  WORKFLOW_COMPARISON = "WORKFLOW_COMPARISON",
  REPORT_GENERATION = "REPORT_GENERATION",
  CONVERSATIONAL_QUERY = "CONVERSATIONAL_QUERY",
}

export enum EmploymentType {
  FULL_TIME = "FULL_TIME",
  PART_TIME = "PART_TIME",
  CONTRACT = "CONTRACT",
  INTERN = "INTERN",
  FREELANCE = "FREELANCE",
  TEMPORARY = "TEMPORARY",
}

export enum EmployeeStatus {
  ACTIVE = "ACTIVE",
  TERMINATED = "TERMINATED",
  ON_LEAVE = "ON_LEAVE",
  RESIGNED = "RESIGNED",
  RETIRED = "RETIRED",
  SUSPENDED = "SUSPENDED",
}
